name: fitrope_app
description: "Fitrope App"
publish_to: 'none'

version: 1.0.0+6

environment:
  sdk: '>=3.5.0-180.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  flutter_design_system:
    git:
      url: https://github.com/dellarosamarco/flutter_design_system.git
      ref: main
  redux_thunk: ^0.4.0
  redux: ^5.0.0
  flutter_redux: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/